---
abstract: 'Convert a Kwiki wiki to a Silki wiki'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0.88
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SilkiX-Converter-Kwiki
requires:
  File::MimeInfo: 0
  File::Slurp: 0
  File::chdir: 0
  HTML::Tidy: 0
  JSON: 0
  Kwiki: 0
  Kwiki::Attachments: 0
  Moose: 0
  MooseX::Getopt: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0
  Path::Class: 0
  Scalar::Util: 0
  Silki: 0.15
  URI::Escape: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SilkiX-Converter-Kwiki
  repository: http://hg.urth.org/hg/SilkiX-Converter-Kwiki
version: 0.02
